/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MinhasReceitasRouteImport } from './routes/minhas-receitas'
import { Route as MinhaDespensaRouteImport } from './routes/minha-despensa'
import { Route as IndexRouteImport } from './routes/index'

const MinhasReceitasRoute = MinhasReceitasRouteImport.update({
  id: '/minhas-receitas',
  path: '/minhas-receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaDespensaRoute = MinhaDespensaRouteImport.update({
  id: '/minha-despensa',
  path: '/minha-despensa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/minha-despensa': typeof MinhaDespensaRoute
  '/minhas-receitas': typeof MinhasReceitasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/minha-despensa': typeof MinhaDespensaRoute
  '/minhas-receitas': typeof MinhasReceitasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/minha-despensa': typeof MinhaDespensaRoute
  '/minhas-receitas': typeof MinhasReceitasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/minha-despensa' | '/minhas-receitas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/minha-despensa' | '/minhas-receitas'
  id: '__root__' | '/' | '/minha-despensa' | '/minhas-receitas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MinhaDespensaRoute: typeof MinhaDespensaRoute
  MinhasReceitasRoute: typeof MinhasReceitasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/minhas-receitas': {
      id: '/minhas-receitas'
      path: '/minhas-receitas'
      fullPath: '/minhas-receitas'
      preLoaderRoute: typeof MinhasReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-despensa': {
      id: '/minha-despensa'
      path: '/minha-despensa'
      fullPath: '/minha-despensa'
      preLoaderRoute: typeof MinhaDespensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MinhaDespensaRoute: MinhaDespensaRoute,
  MinhasReceitasRoute: MinhasReceitasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
