/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as MinhasReceitasRouteImport } from './routes/minhas-receitas'
import { Route as MinhaDespensaRouteImport } from './routes/minha-despensa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListaComprasRouteImport } from './routes/lista-compras'
import { Route as FotoRouteImport } from './routes/foto'
import { Route as DietaRouteImport } from './routes/dieta'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasReceitasRoute = MinhasReceitasRouteImport.update({
  id: '/minhas-receitas',
  path: '/minhas-receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaDespensaRoute = MinhaDespensaRouteImport.update({
  id: '/minha-despensa',
  path: '/minha-despensa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaComprasRoute = ListaComprasRouteImport.update({
  id: '/lista-compras',
  path: '/lista-compras',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoRoute = FotoRouteImport.update({
  id: '/foto',
  path: '/foto',
  getParentRoute: () => rootRouteImport,
} as any)
const DietaRoute = DietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dieta': typeof DietaRoute
  '/foto': typeof FotoRoute
  '/lista-compras': typeof ListaComprasRoute
  '/login': typeof LoginRoute
  '/minha-despensa': typeof MinhaDespensaRoute
  '/minhas-receitas': typeof MinhasReceitasRoute
  '/pagamento': typeof PagamentoRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/receitas': typeof ReceitasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dieta': typeof DietaRoute
  '/foto': typeof FotoRoute
  '/lista-compras': typeof ListaComprasRoute
  '/login': typeof LoginRoute
  '/minha-despensa': typeof MinhaDespensaRoute
  '/minhas-receitas': typeof MinhasReceitasRoute
  '/pagamento': typeof PagamentoRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/receitas': typeof ReceitasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dieta': typeof DietaRoute
  '/foto': typeof FotoRoute
  '/lista-compras': typeof ListaComprasRoute
  '/login': typeof LoginRoute
  '/minha-despensa': typeof MinhaDespensaRoute
  '/minhas-receitas': typeof MinhasReceitasRoute
  '/pagamento': typeof PagamentoRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/receitas': typeof ReceitasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/dieta'
    | '/foto'
    | '/lista-compras'
    | '/login'
    | '/minha-despensa'
    | '/minhas-receitas'
    | '/pagamento'
    | '/perfil'
    | '/planos'
    | '/receitas'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/dieta'
    | '/foto'
    | '/lista-compras'
    | '/login'
    | '/minha-despensa'
    | '/minhas-receitas'
    | '/pagamento'
    | '/perfil'
    | '/planos'
    | '/receitas'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/dieta'
    | '/foto'
    | '/lista-compras'
    | '/login'
    | '/minha-despensa'
    | '/minhas-receitas'
    | '/pagamento'
    | '/perfil'
    | '/planos'
    | '/receitas'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  DietaRoute: typeof DietaRoute
  FotoRoute: typeof FotoRoute
  ListaComprasRoute: typeof ListaComprasRoute
  LoginRoute: typeof LoginRoute
  MinhaDespensaRoute: typeof MinhaDespensaRoute
  MinhasReceitasRoute: typeof MinhasReceitasRoute
  PagamentoRoute: typeof PagamentoRoute
  PerfilRoute: typeof PerfilRoute
  PlanosRoute: typeof PlanosRoute
  ReceitasRoute: typeof ReceitasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-receitas': {
      id: '/minhas-receitas'
      path: '/minhas-receitas'
      fullPath: '/minhas-receitas'
      preLoaderRoute: typeof MinhasReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-despensa': {
      id: '/minha-despensa'
      path: '/minha-despensa'
      fullPath: '/minha-despensa'
      preLoaderRoute: typeof MinhaDespensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista-compras': {
      id: '/lista-compras'
      path: '/lista-compras'
      fullPath: '/lista-compras'
      preLoaderRoute: typeof ListaComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foto': {
      id: '/foto'
      path: '/foto'
      fullPath: '/foto'
      preLoaderRoute: typeof FotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieta': {
      id: '/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof DietaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  DietaRoute: DietaRoute,
  FotoRoute: FotoRoute,
  ListaComprasRoute: ListaComprasRoute,
  LoginRoute: LoginRoute,
  MinhaDespensaRoute: MinhaDespensaRoute,
  MinhasReceitasRoute: MinhasReceitasRoute,
  PagamentoRoute: PagamentoRoute,
  PerfilRoute: PerfilRoute,
  PlanosRoute: PlanosRoute,
  ReceitasRoute: ReceitasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
