/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as MinhasReceitasRouteImport } from './routes/minhas-receitas'
import { Route as MinhaDespensaRouteImport } from './routes/minha-despensa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'

const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasReceitasRoute = MinhasReceitasRouteImport.update({
  id: '/minhas-receitas',
  path: '/minhas-receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaDespensaRoute = MinhaDespensaRouteImport.update({
  id: '/minha-despensa',
  path: '/minha-despensa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/minha-despensa': typeof MinhaDespensaRoute
  '/minhas-receitas': typeof MinhasReceitasRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/minha-despensa': typeof MinhaDespensaRoute
  '/minhas-receitas': typeof MinhasReceitasRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/minha-despensa': typeof MinhaDespensaRoute
  '/minhas-receitas': typeof MinhasReceitasRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/minha-despensa'
    | '/minhas-receitas'
    | '/receitas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/minha-despensa'
    | '/minhas-receitas'
    | '/receitas'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/login'
    | '/minha-despensa'
    | '/minhas-receitas'
    | '/receitas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  MinhaDespensaRoute: typeof MinhaDespensaRoute
  MinhasReceitasRoute: typeof MinhasReceitasRoute
  ReceitasRoute: typeof ReceitasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-receitas': {
      id: '/minhas-receitas'
      path: '/minhas-receitas'
      fullPath: '/minhas-receitas'
      preLoaderRoute: typeof MinhasReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-despensa': {
      id: '/minha-despensa'
      path: '/minha-despensa'
      fullPath: '/minha-despensa'
      preLoaderRoute: typeof MinhaDespensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  MinhaDespensaRoute: MinhaDespensaRoute,
  MinhasReceitasRoute: MinhasReceitasRoute,
  ReceitasRoute: ReceitasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
